// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhentjbiqaogzhfrbzyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZW50amJpcWFvZ3poZnJienliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mjc4MzAsImV4cCI6MjA2ODQwMzgzMH0.1NX8DYepGtOwFZZIuF1KwNRLLOFca_t68QM32Znvpa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});